steps:
  - label: ":docker: build + push + rmi"
    env:
      HTTP_PROXY: "http://proxy.ops.scentregroup.io:3128"
      NODE_EXPORTER_VERSION: "0.15.2"
    command:
      - docker build --build-arg http_proxy=\${HTTP_PROXY} --build-arg https_proxy=\${HTTP_PROXY} -t ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:\${NODE_EXPORTER_VERSION} -t ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:latest ./
      - docker push ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:\${NODE_EXPORTER_VERSION}
      - docker push ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:latest
      - docker rmi ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:\${NODE_EXPORTER_VERSION}
      - docker rmi ${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}:latest
